# Site settings
title: Abington 10K and Fun Run
email: abington10k@gmail.com
description: "A yearly 10k race and 2k fun run around the picturesque villages of Little and Great Abington, Cambridgeshire."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abington10k.org.uk" # the base hostname & protocol for your site

twitter_username: abington10k

# Build settings
markdown: kramdown
